jaegertracing/jaeger-lib

- metrics/local.go
- metrics/local_test.go
- metrics/metrics_test.go
> Support tagged metrics in local backend

- .travis.yml
- glide.lock
- glide.yaml
- metrics/counter.go
- metrics/go-kit/expvar/factory.go
- metrics/go-kit/expvar/factory_test.go
- metrics/go-kit/factory.go
- metrics/go-kit/factory_test.go
- metrics/go-kit/metrics.go
- metrics/go-kit/metrics_test.go
This implements the pattern I was asking for in https://github.com/go-kit/kit/issues/378, simplified for our needs.
> Add adapters for go-kit metrics and a factory for expvar

- glide.lock
- glide.yaml
- metrics/tally/factory_test.go
This allows downstreams to use either tally v2.1 or the latest version (v3)
> Allow jaeger-lib to be used with tally >= 2.1, < 4

- metrics/go-kit/factory.go
- metrics/go-kit/factory_test.go
- metrics/go-kit/prometheus/factory.go
- metrics/go-kit/prometheus/factory_test.go
Prometheus does not allow '-' or '.' in metric names.
Cf: https://github.com/uber/jaeger/issues/273
> Allow overriding scope and tags separator

- glide.lock
- glide.yaml
- metrics/go-kit/influx/factory.go
- metrics/go-kit/influx/factory_test.go
Adds support for reporting metrics to InfluxDB.
I used existing support for go-kit metrics.
For now it's not possible to specify histogram buckets because they are [hardcoded in go-kit](https://github.com/go-kit/kit/blob/master/metrics/influx/influx.go#L149).
> Support influx metrics

- client/log/go-kit/logger.go
- client/log/go-kit/logger_test.go
- glide.lock
Fixes uber/jaeger-client-go#200
This is my first contribution to any Uber software, I'm not particularly familiar with your code guides (tried to follow some practices based on code and contrib guide though), so think of it as a first draft and shoot at it.
> Add a Jaeger client logger wrapper around go-kit logger

- metrics/prometheus/cache.go
- metrics/prometheus/factory.go
- metrics/prometheus/factory_test.go
Required by https://github.com/jaegertracing/jaeger/issues/360 and https://github.com/jaegertracing/jaeger/issues/273
Prometheus requires pre-declaring all metrics and their labels, and for a given metric name only one set of labels is allowed, otherwise panic occurs.
The approach here is to cache metric vectors registered with Prometheus using metric's name and a sorted list of labels as the cache key. This allows creating Jaeger metrics objects multiple times even with the same name and a set of tags.
> Support Prometheus metrics directly

- CHANGELOG.md
- metrics/prometheus/factory.go
- metrics/prometheus/factory_test.go
This is a breaking change, but I don't suppose anyone had a change to use the new `prometheus.New()` API that was only released 2d ago.
> Change prometheus.New() to accept options rather than fixed arguments

- utils/rate_limiter.go
- utils/rate_limiter_test.go
Signed-off-by: Isaac Hier <ihier@uber.com>
> Move rate limiter from client to jaeger-lib

- metrics/adapters/cache.go
- metrics/adapters/cache_test.go
- metrics/adapters/factory.go
- metrics/adapters/factory_test.go
- metrics/adapters/tagless.go
- metrics/expvar/factory.go
- metrics/expvar/factory_test.go
- metrics/go-kit/expvar/factory.go
- metrics/go-kit/prometheus/factory.go
- metrics/prometheus/cache.go
Required for https://github.com/jaegertracing/jaeger/issues/716
Add a new module `metrics/adapters` that provide caching of the created metrics objects and the common functionality of managing namespaces and flattening tags into metric id string.
> Reimplement expvar metrics to be tolerant of duplicates

- metrics/prometheus/factory.go
I am using the following versions:
```yaml
- package: github.com/prometheus/client_golang
version: ~0.9.0-pre1
- package: github.com/uber/jaeger-client-go
version: ^2.12.0
- name: github.com/uber/jaeger-lib
version: 4267858c0679cd4e47cefed8d7f70fd386cfb567
```
If we use a histogram and try to create a new tracer (using `jaeger-client-go`) with metrics, for example:
```Go
var reg prometheus.Registerer
// set the value of reg to some Prometheus registry here
factory := jaegerprom.New(jaegerprom.WithRegisterer(reg))
tracer, closer, err := config.New(appName, jaegercfg.Metrics(factory))
```
I get the following error:
```bash
vendor/github.com/uber/jaeger-lib/metrics/prometheus/factory.go:143:12: cannot use hv.WithLabelValues(f.tagsAsLabelValues(labelNames, tags)...) (type prometheus.Observer) …
```
> Use an interface instead of a concrete type

- metrics/local.go
- metrics/local_test.go
- metrics/prometheus/factory.go
- metrics/prometheus/factory_test.go
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>
> Change metrics naming scheme

- metrics/adapters/cache_test.go
- metrics/adapters/factory_test.go
- metrics/keys.go
- metrics/metrics.go
- metrics/metrics_test.go
- metrics/multi/multi_test.go
- metrics/testutils/metricstest/local.go
- metrics/testutils/metricstest/local_test.go
- metrics/testutils/metricstest/metricstest.go
- metrics/testutils/metricstest/metricstest_test.go
- Applications using jaeger-client-go pull in the local backend although it is unused
and more importantly, they also depend on the unmaintained
https://github.com/codahale/hdrhistogram
This can raise red flags when trying to use jaeger-client-go in organizations
were dependencies are closely scrutinized.
- This PR does *not* remove the dependency on hdrhistogram and thus
does not solve #32.
-   Now the local backend is in a new metrics/local package that is not
pulled in via the client API. Beware that this an API break because
"metrics" no longer has the same functions.
-  To minimize the API change, GetKey() is kept in "metrics" because it
doesn't depend on the local backend.
-  To break a dependency cycle (metrics -> local -> metrics),
test_metrics.go has to be in a metrics_test …
> metrics: break out local backend into metrics/local

- .travis.yml
- Makefile
- Resolves #55.
- Travis changes to use Go 1.11.1.
> Upgrade to Go 1.11.1 in Travis CI

- metrics/prometheus/factory.go
- metrics/prometheus/factory_test.go
As discussed in the [prometheus documentation](https://prometheus.io/docs/practices/naming/#metric-names), "an accumulating count has total as a suffix".
If the counter does not have the `_total` suffix, then it will be added.
This change will also be required to bring the Go tracer inline with the metrics being reported by the Java tracer, which is using the micrometer library that applies a similar transformation on the counter metric names. See https://github.com/jaegertracing/jaeger-client-java/pull/564.
Signed-off-by: Gary Brown <gary@brownuk.com>
> Add _total suffix for counters reported to prometheus

- metrics/adapters/cache_test.go
- metrics/adapters/factory.go
- metrics/adapters/factory_test.go
- metrics/adapters/tagless.go
- metrics/expvar/factory.go
- metrics/expvar/factory_test.go
- metrics/factory.go
- metrics/go-kit/factory.go
- metrics/go-kit/factory_test.go
- metrics/go-kit/influx/factory_test.go
- metrics/metrics.go
- metrics/metrics_test.go
- metrics/metricstest/local.go
- metrics/metricstest/local_test.go
- metrics/multi/multi.go
- metrics/multi/multi_test.go
- metrics/prometheus/factory.go
- metrics/prometheus/factory_test.go
- metrics/tally/factory.go
- metrics/tally/factory_test.go
Resolves #60 
Signed-off-by: Gary Brown <gary@brownuk.com>
> Add metric description to factory API

- metrics/adapters/cache.go
- metrics/adapters/cache_test.go
- metrics/adapters/factory.go
- metrics/adapters/factory_test.go
- metrics/adapters/tagless.go
- metrics/expvar/factory.go
- metrics/expvar/factory_test.go
- metrics/factory.go
- metrics/go-kit/factory.go
- metrics/go-kit/factory_test.go
- metrics/go-kit/influx/factory_test.go
- metrics/go-kit/metrics.go
- metrics/go-kit/metrics_test.go
- metrics/histogram.go
- metrics/metrics.go
- metrics/metrics_test.go
- metrics/metricstest/local.go
- metrics/metricstest/local_test.go
- metrics/multi/multi.go
- metrics/multi/multi_test.go
- metrics/prometheus/factory.go
- metrics/prometheus/factory_test.go
- metrics/tally/factory.go
- metrics/tally/factory_test.go
- metrics/tally/metrics.go
Resolves #62 
Signed-off-by: Gary Brown <gary@brownuk.com>
> Add first class support for Histograms

- .travis.yml
- Makefile
- Removes GO15VENDOREXPERIMENT variable on development and CI.
- Even at the inception of the project, as this project supports only Go 1.6+ 321ba1b6f06ecca380cf284172eb1ee17e71c37d, we do not need to have `GO15VENDOREXPERIMENT`.
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>
> Remove GO15VENDOREXPERIMENT variable

- metrics/metrics.go
Typo in metrics Init method docs.
Rename method in doc.
> Fix typo in metrics Init method docs

- Gopkg.lock
- Gopkg.toml
- Makefile
- glide.lock
- glide.yaml
- metrics/go-kit/influx/factory_test.go
> Upgrade Prometheus client to 1.1 and go-kit to 0.9

- Gopkg.lock
- Gopkg.toml
- glide.lock
- glide.yaml
- metrics/metricstest/local.go
The codahale/hdrhistogram repo has been transferred under the github HdrHstogram umbrella with the help from the original author in Sept 2020 (new repo url https://github.com/HdrHistogram/hdrhistogram-go). The main reasons are to group all implementations under the same roof and to provide more active contribution from the community as the original repository was archived several years ago.
Unfortunately such URL change will break go applications that depend on this library directly or indirectly, as discussed here.
The dependency URL should be modified to point to the new repository URL. The tag "v0.9.0" was applied at the point of transfer and will reflect the exact code that was frozen in the original repository.
This PR updates the dependency, thus fixes #81
> [fix] updated hdrhistogram dependency to HdrHistogram org repo

- Gopkg.lock
- metrics/fork/fork.go
- metrics/fork/fork_test.go
- Required changes for https://github.com/jaegertracing/jaeger/pull/2496
- Implement fork.Factory that delegates metrics with
specific namespaces to different factory, otherwise
default factory is used.
> Implement fork.Factory

- Makefile
Since it now defaults to `on` in Go 1.16
> Set GO111MODULE=off

- metrics/prometheus/factory.go
- metrics/prometheus/factory_test.go
Signed-off-by: Konstantinos Moraitis <k.moraitis9@gmail.com>
- Resolves https://github.com/jaegertracing/jaeger-lib/issues/89
- The prometheus factory determines which buckets to use when creating a Histogram. 
If the histogram options, provided as arguments, are empty, then the factory uses the default buckets.
> Apply default buckets in Prometheus Factory

- metrics/prometheus/factory.go
- metrics/prometheus/factory_test.go
Signed-off-by: Konstantinos Moraitis <k.moraitis9@gmail.com>
- In the same way as the `Histogram` metric in the Prometheus factory (https://github.com/jaegertracing/jaeger-lib/issues/89), we should also consider using the default buckets with the `Timer` metric.
- The prometheus factory determines which buckets to use when creating a Timer.
If the buckets in timer options, provided as arguments, are empty, then the factory uses the default buckets.
> Apply default buckets for Timer metric in Prometheus Factory
